#pragma once
#include "const_expr.hpp"
#include <cmath>

// Memory configuration:
#define NUM_ADDRESS_BITS 32
#define BLOCK_SIZE 16
#define BLOCK_SIZE_LOG2 bitsNeeded(BLOCK_SIZE)

// Prefetching configuration:
#define MAX_PREDICTION_CONFIDENCE 15
#define PREDICTION_CONFIDENCE_THRESHOLD 3
#define PREDICTION_CONFIDENCE_INCREASE 1
#define PREDICTION_CONFIDENCE_DECREASE -2
#define MAX_PREDICTION_CONFIDENCE_LOG2 bitsNeeded(MAX_PREDICTION_CONFIDENCE)

#define MAX_PREFETCHING_DEGREE 1

#define REGION_BLOCK_SIZE 32
#define REGION_BLOCK_SIZE_LOG2 bitsNeeded(REGION_BLOCK_SIZE)

// Dictionary configuration:
#define NUM_CLASSES 12
#define NUM_CLASSES_INCLUDING_NULL (NUM_CLASSES + 1)
#define NUM_CLASSES_LOG2 bitsNeeded(NUM_CLASSES_INCLUDING_NULL)
#define DICTIONARY_LFU_MAX_CONFIDENCE 127
#define DICTIONARY_LFU_CONFIDENCE_STEP 16
#define DICTIONARY_LFU_INITIAL_CONFIDENCE 0
#define DICTIONARY_LFU_CONFIDENCE_LOG2 bitsNeeded(DICTIONARY_LFU_MAX_CONFIDENCE)

// SVM configuration:
#define SEQUENCE_LENGTH 8
#define SVM_LEARNING_RATE_LOG2 6
#define SVM_WEIGHT_MAX_ABSOLUTE_LOG2 5
#define SVM_WEIGHT_NUM_BITS (1 + SVM_WEIGHT_MAX_ABSOLUTE_LOG2 + SVM_LEARNING_RATE_LOG2)

// Input buffer configuration:
#define IB_NUM_SETS 64
#define IB_NUM_SETS_LOG2 bitsNeeded(IB_NUM_SETS)
#define IB_NUM_WAYS 2
#define IB_NUM_TAG_BITS (NUM_ADDRESS_BITS - IB_NUM_SETS_LOG2 - BLOCK_SIZE_LOG2)
#define IB_NUM_LRU_COUNTER_BITS 1
#define IB_MAX_LRU_COUNTER (1 << (IB_NUM_LRU_COUNTER_BITS - 1))


