#pragma once
#include "const_expr.hpp"
#include <cmath>

// C-sim debug:
#define CSIM_DEBUG_no

// Memory configuration:
#define NUM_ADDRESS_BITS 32
#define WORD_BYTES_SIZE_LOG2 2
#define WORD_BYTES_SIZE (1 << WORD_BYTES_SIZE_LOG2)
#define BLOCK_SIZE_LOG2 6
#define BLOCK_SIZE (1 << BLOCK_SIZE_LOG2)
#define NUM_BLOCK_ADDRESS_BITS (NUM_ADDRESS_BITS - BLOCK_SIZE_LOG2)
#define NUM_DELTA_BITS (NUM_BLOCK_ADDRESS_BITS + 1)

#define REGION_BLOCK_SIZE_LOG2 6
#define REGION_BLOCK_SIZE (1 << REGION_BLOCK_SIZE_LOG2)
#define NUM_REGION_ADDRESS_BITS (NUM_ADDRESS_BITS - REGION_BLOCK_SIZE_LOG2 - BLOCK_SIZE_LOG2)

#define START_CACHEABLE_MEM_REGION 0x0
#define END_CACHEABLE_MEM_REGION 0x40000000

// Interface configuration:
#define AXI_DATA_SIZE_BITS 32
#define AXI_DATA_SIZE_BYTES_LOG2 2
#define AXI_BURST_LENGTH_BITS 8
#define AXI_BURST_SIZE_BITS 7
#define AXI_BURST_SIZE_BITFIELD_LOG2 3

#define AXI_WRAP_BURST_LENGTH_LOG2 2 // Number of transfers in WRAP burst type: 2, 4, 8, 16
#define AXI_BLOCK_BURST_LENGTH_LOG2 (AXI_BURST_LENGTH_BITS + AXI_BURST_SIZE_BITS - BLOCK_SIZE_LOG2)
#define	AXI_MAX_BURST_BLOCK_LOG2 2


// Prefetching configuration:
#define MAX_PREDICTION_CONFIDENCE 15
#define PREDICTION_CONFIDENCE_THRESHOLD 7
#define PREDICTION_CONFIDENCE_INCREASE 1
#define PREDICTION_CONFIDENCE_DECREASE -4
#define BURST_PREDICTION_CONFIDENCE_THRESHOLD 9
#define BURST_PREDICTION_CONFIDENCE_INCREASE 1
#define BURST_PREDICTION_CONFIDENCE_DECREASE -6
#define MAX_PREDICTION_CONFIDENCE_LOG2 bitsNeeded(MAX_PREDICTION_CONFIDENCE)
#define MAX_PREFETCHING_DEGREE 1

// Dictionary configuration:
#define NUM_CLASSES 7
#define NUM_CLASSES_INCLUDING_NULL (NUM_CLASSES + 1)
#define NUM_CLASSES_LOG2 bitsNeeded(NUM_CLASSES)
#define NUM_CLASSES_INCLUDING_NULL_LOG2 bitsNeeded(NUM_CLASSES_INCLUDING_NULL)
#define DICTIONARY_LFU_MAX_CONFIDENCE 127
#define DICTIONARY_LFU_CONFIDENCE_STEP 16
#define DICTIONARY_LFU_INITIAL_CONFIDENCE 0
#define DICTIONARY_LFU_CONFIDENCE_LOG2 bitsNeeded(DICTIONARY_LFU_MAX_CONFIDENCE)

// SVM configuration:
#define SEQUENCE_LENGTH 6
#define SVM_LEARNING_RATE_LOG2 6
#define SVM_WEIGHT_MAX_ABSOLUTE_LOG2 5
#define NUM_SVM_WEIGHT_BITS (1 + SVM_WEIGHT_MAX_ABSOLUTE_LOG2 + SVM_LEARNING_RATE_LOG2)
#define NUM_DISTANCE_BITS (NUM_SVM_WEIGHT_BITS + bitsNeeded(SEQUENCE_LENGTH))

#define NUM_BURST_CLASSES 4
#define NUM_BURST_CLASSES_INCLUDING_NULL (NUM_BURST_CLASSES + 1)

// Input buffer configuration:
#define IB_NUM_SETS 64
#define IB_NUM_SETS_LOG2 bitsNeeded(IB_NUM_SETS)
#define IB_NUM_WAYS 2
#define IB_NUM_WAYS_LOG2 bitsNeeded(IB_NUM_WAYS)
#define IB_NUM_WAYS_INCLUDING_NULL_LOG2 bitsNeeded(IB_NUM_WAYS + 1)
#define IB_NUM_TAG_BITS (NUM_ADDRESS_BITS - IB_NUM_SETS_LOG2)
#define IB_NUM_REGION_TAG_BITS (NUM_REGION_ADDRESS_BITS - IB_NUM_SETS_LOG2)
#define IB_NUM_LRU_COUNTER_BITS 1
#define IB_MAX_LRU_COUNTER ((1 << IB_NUM_LRU_COUNTER_BITS) - 1)

// Forwarding buffer configuration:
#define FORWARDING_DEPTH 2
#define FORWARDING_DEPTH_LOG2 bitsNeeded(FORWARDING_DEPTH)
#define CONF_FORWARDING_DEPTH 2
#define CONF_FORWARDING_DEPTH_LOG2 bitsNeeded(CONF_FORWARDING_DEPTH)


